micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
  views:
    rocker:
      enabled: false


neo4j:
  uri: ${GRAPHENEDB_BOLT_URL}
  username: ${GRAPHENEDB_BOLT_USER}
  password: ${GRAPHENEDB_BOLT_PASSWORD}
  encryption: true
